---
title: "test"
listing:
  contents: posts
  sort: "date-desc"
  categories: true
  type: table
  fields: [date, title]
---

This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.

### resume

- intercept iframe widget to strip its superfluous ui elements eg .gsc-header
- remove quarto.yaml wide giscus and insert giscus manually per page with include header after
- project is quarto-giscus a minimal demonstrator and quarto render to build it

### legacy

I think this script is inserted by Quarto we clone it as assets/giscus.html for insert after body

<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "r-leyshon/quarto-giscus";
    script.dataset.repoId = "R_kgDOMkzHGg";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOMkzHGs4ChvwI";
    script.dataset.mapping = "url";
    script.dataset.reactionsEnabled = "0";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "bottom";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>

format:
  html:
    theme: lumen
    toc: true
    css: assets/cobalt.css
    comments:
      giscus: 
        repo: r-leyshon/quarto-giscus
        repo-id: R_kgDOMkzHGg
        category: Announcements
        category-id: DIC_kwDOMkzHGs4ChvwI
        reactions-enabled: false
        mapping: url
        input-position: "bottom"
        theme: noborder_gray
        loading: "lazy"

theme: "url:https://github.com/fischerpj/qwgsc/assets/cobalt.css?v=2"

https://fischerpj.github.io/qwgsc/

https://giscus.app/en/widget?origin where route is en/widget
we test manually src="https://giscus_proxy.pjafischer.workers.dev/en/widget?origin and it works echo

<iframe class="giscus-frame" title="Comments" scrolling="no" allow="clipboard-write" src="https://giscus_proxy.pjafischer.workers.dev/en/widget?origin=http%3A%2F%2F192.168.8.122%3A8787%2Ffiles%2Fquarto-giscus%2Fdocs%2Findex.html&amp;session=b9031201987b2757d82c090dOnqoMX%2BPUQhNTSRC8LmbGKX0wnlpqAvr71A1uSeSuMxOtNdEUPftGPxOHuE42l4paCHVdooxBwWLAuC15wjLnzNcakTRSMNZydBOdey05FlfGQaXW%2BnKqYHidQ8%3D&amp;theme=noborder_gray&amp;reactionsEnabled=0&amp;emitMetadata=0&amp;inputPosition=bottom&amp;repo=r-leyshon%2Fquarto-giscus&amp;repoId=R_kgDOMkzHGg&amp;category=Announcements&amp;categoryId=DIC_kwDOMkzHGs4ChvwI&amp;strict=0&amp;description=&amp;backLink=http%3A%2F%2F192.168.8.122%3A8787%2Ffiles%2Fquarto-giscus%2Fdocs%2Findex.html&amp;term=http%3A%2F%2F192.168.8.122%3A8787%2Ffiles%2Fquarto-giscus%2Fdocs%2Findex.html" style="height: 281px;"></iframe>

<!--
<details>
<summary>Show comments</summary>
<p>end of details</details>
</details>-->

